//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miriot.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Miriot.Resources.Strings.fr", typeof(Strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        public static string Compact {
            get {
                return ResourceManager.GetString("Compact", resourceCulture);
            }
        }
        
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        public static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        public static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        public static string DetectingMiriot {
            get {
                return ResourceManager.GetString("DetectingMiriot", resourceCulture);
            }
        }
        
        public static string GiveAName {
            get {
                return ResourceManager.GetString("GiveAName", resourceCulture);
            }
        }
        
        public static string GiveANameMessage {
            get {
                return ResourceManager.GetString("GiveANameMessage", resourceCulture);
            }
        }
        
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        public static string MyDevices {
            get {
                return ResourceManager.GetString("MyDevices", resourceCulture);
            }
        }
        
        public static string NoConfiguration {
            get {
                return ResourceManager.GetString("NoConfiguration", resourceCulture);
            }
        }
        
        public static string NoMirrorDetected {
            get {
                return ResourceManager.GetString("NoMirrorDetected", resourceCulture);
            }
        }
        
        public static string RetrievingUser {
            get {
                return ResourceManager.GetString("RetrievingUser", resourceCulture);
            }
        }
        
        public static string RetrievingUserFailed {
            get {
                return ResourceManager.GetString("RetrievingUserFailed", resourceCulture);
            }
        }
        
        public static string SelectMiriot {
            get {
                return ResourceManager.GetString("SelectMiriot", resourceCulture);
            }
        }
        
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        public static string UnableToSaveAccount {
            get {
                return ResourceManager.GetString("UnableToSaveAccount", resourceCulture);
            }
        }
        
        public static string UnableToUpdateAccount {
            get {
                return ResourceManager.GetString("UnableToUpdateAccount", resourceCulture);
            }
        }
    }
}
